version: '3.8'

services:
  ###############################################################################
  # Three Roots Investment Website
  ###############################################################################
  three-roots-web:
    image: ${DOCKER_HUB_USERNAME}/three-roots-frontend:${THREE_ROOTS_VERSION:-latest}
    container_name: three-roots-website
    restart: unless-stopped
    ports:
      - "${THREE_ROOTS_PORT:-3000}:80"
    networks:
      - net
    environment:
      - NGINX_HOST=${APP_DOMAIN:-localhost}
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.three-roots.description=Three Roots Investment Website"
      - "com.three-roots.service=frontend"

  ###############################################################################
  # Redis
  ###############################################################################
  redis:
    image: redis:7.4-bookworm
    container_name: mre-redis
    restart: unless-stopped
    environment:
      - REDIS_PORT=6379
    expose:
      - '6379'
    volumes:
      - redis_data:/data
    command: [
        'sh',
        '-c',
        'docker-entrypoint.sh --requirepass ${REDIS_PASSWORD} --loglevel warning'
      ]
    networks:
      - net
    labels:
      - "com.three-roots.description=Redis Cache"
      - "com.three-roots.service=cache"

  ###############################################################################
  # MongoDB
  ###############################################################################
  mongo:
    image: mongo:7
    container_name: mre-mongo
    restart: unless-stopped
    environment:
      - MONGO_PORT=27017
    command: --quiet --logpath /dev/null
    expose:
      - '27017'
    volumes:
      - mongodb_data:/data/db
      - backup_data:/backup
    networks:
      - net
    labels:
      - "com.three-roots.description=MongoDB Database"
      - "com.three-roots.service=database"

  ###############################################################################
  # Reverse Proxy (Caddy)
  ###############################################################################
  reverse-proxy:
    image: caddy:latest
    container_name: mre-caddy
    restart: unless-stopped
    command: caddy reverse-proxy --from ${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}:${APP_PORT:-80} --to gateway:8080
    ports:
      - "${APP_PORT:-80}:${APP_PORT:-80}"
      - "443:443"
    networks:
      - net
    depends_on:
      - gateway
    labels:
      - "com.three-roots.description=Reverse Proxy"
      - "com.three-roots.service=proxy"

  ###############################################################################
  # Gateway
  ###############################################################################
  gateway:
    image: ghcr.io/microrealestate/microrealestate/gateway:${MRE_VERSION:-latest}
    container_name: mre-gateway
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOGGER_LEVEL=info
      - PORT=8080
      - EXPOSE_FRONTENDS=true
      - AUTHENTICATOR_URL=http://authenticator:8000
      - API_URL=http://api:8200/api/v2
      - PDFGENERATOR_URL=http://pdfgenerator:8300/pdfgenerator
      - EMAILER_URL=http://emailer:8400/emailer
      - LANDLORD_FRONTEND_URL=http://landlord-frontend:8180
      - LANDLORD_BASE_PATH=/landlord
      - TENANT_FRONTEND_URL=http://tenant-frontend:8190
      - TENANT_BASE_PATH=/tenant
      - APP_DOMAIN=${APP_DOMAIN:-localhost}:${APP_PORT:-80}
      - CORS_ENABLED=true
      - TENANTAPI_URL=http://tenantapi:8250/tenantapi
    ports:
      - "8081:8080"
    networks:
      - net
    depends_on:
      - authenticator
      - api
      - tenantapi
      - pdfgenerator
      - emailer
    labels:
      - "com.three-roots.description=MRE API Gateway"
      - "com.three-roots.service=gateway"

  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    image: ghcr.io/microrealestate/microrealestate/authenticator:${MRE_VERSION:-latest}
    container_name: mre-authenticator
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8000
      - LOGGER_LEVEL=info
      - REDIS_URL=redis://redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - RESET_TOKEN_SECRET=${RESET_TOKEN_SECRET}
      - APPCREDZ_TOKEN_SECRET=${APPCREDZ_TOKEN_SECRET}
      - MONGO_URL=${MONGO_URL:-mongodb://mongo/mredb}
      - EMAILER_URL=http://emailer:8400/emailer
      - SIGNUP=true
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - APP_PROTOCOL=${APP_PROTOCOL:-http}
    expose:
      - '8000'
    networks:
      - net
    depends_on:
      - redis
      - mongo
      - emailer
    labels:
      - "com.three-roots.description=MRE Authentication Service"
      - "com.three-roots.service=auth"

  ###############################################################################
  # PDF Generator
  ###############################################################################
  pdfgenerator:
    image: ghcr.io/microrealestate/microrealestate/pdfgenerator:${MRE_VERSION:-latest}
    container_name: mre-pdfgenerator
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8300
      - LOGGER_LEVEL=info
      - MONGO_URL=${MONGO_URL:-mongodb://mongo/mredb}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - CIPHER_KEY=${CIPHER_KEY}
      - CIPHER_IV_KEY=${CIPHER_IV_KEY}
      - UPLOAD_MAX_SIZE=2000000000
    expose:
      - '8300'
    networks:
      - net
    depends_on:
      - mongo
    labels:
      - "com.three-roots.description=MRE PDF Generator"
      - "com.three-roots.service=pdfgen"

  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    image: ghcr.io/microrealestate/microrealestate/emailer:${MRE_VERSION:-latest}
    container_name: mre-emailer
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ALLOW_SENDING_EMAILS=true
      - PORT=8400
      - LOGGER_LEVEL=info
      - LANDLORD_APP_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}:${APP_PORT:-80}/landlord
      - TENANT_APP_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}:${APP_PORT:-80}/tenant
      - MONGO_URL=${MONGO_URL:-mongodb://mongo/mredb}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - CIPHER_KEY=${CIPHER_KEY}
      - CIPHER_IV_KEY=${CIPHER_IV_KEY}
      - PDFGENERATOR_URL=http://pdfgenerator:8300/pdfgenerator
      # Email service configuration
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_REPLY_TO=${EMAIL_REPLY_TO}
      - EMAIL_BCC=${EMAIL_BCC}
    expose:
      - '8400'
    networks:
      - net
    depends_on:
      - mongo
      - pdfgenerator
    labels:
      - "com.three-roots.description=MRE Email Service"
      - "com.three-roots.service=email"

  ###############################################################################
  # API
  ###############################################################################
  api:
    image: ghcr.io/microrealestate/microrealestate/api:${MRE_VERSION:-latest}
    container_name: mre-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8200
      - LOGGER_LEVEL=info
      - MONGO_URL=${MONGO_URL:-mongodb://mongo/mredb}
      - EMAILER_URL=http://emailer:8400/emailer
      - PDFGENERATOR_URL=http://pdfgenerator:8300/pdfgenerator
      - RESTORE_DB=false
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - CIPHER_KEY=${CIPHER_KEY}
      - CIPHER_IV_KEY=${CIPHER_IV_KEY}
    volumes:
      - backup_data:/usr/app/backup
    expose:
      - '8200'
    networks:
      - net
    depends_on:
      - mongo
      - emailer
      - pdfgenerator
    labels:
      - "com.three-roots.description=MRE Main API"
      - "com.three-roots.service=api"

  ###############################################################################
  # Tenant API
  ###############################################################################
  tenantapi:
    image: ghcr.io/microrealestate/microrealestate/tenantapi:${MRE_VERSION:-latest}
    container_name: mre-tenantapi
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8250
      - LOGGER_LEVEL=info
      - MONGO_URL=${MONGO_URL:-mongodb://mongo/mredb}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    expose:
      - '8250'
    networks:
      - net
    depends_on:
      - mongo
    labels:
      - "com.three-roots.description=MRE Tenant API"
      - "com.three-roots.service=tenant-api"

  ###############################################################################
  # Landlord Frontend
  ###############################################################################
  landlord-frontend:
    image: ghcr.io/microrealestate/microrealestate/landlord-frontend:${MRE_VERSION:-latest}
    container_name: mre-landlord-frontend
    restart: unless-stopped
    environment:
      - BASE_PATH=/landlord
      - PORT=8180
      - DOCKER_GATEWAY_URL=http://gateway:8080
      - CORS_ENABLED=true
      - GATEWAY_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}:${APP_PORT:-80}
      - NODE_ENV=production
      - SIGNUP=true
    expose:
      - '8180'
    networks:
      - net
    depends_on:
      - gateway
    labels:
      - "com.three-roots.description=MRE Landlord Frontend"
      - "com.three-roots.service=landlord-ui"

  ###############################################################################
  # Tenant Frontend
  ###############################################################################
  tenant-frontend:
    image: ghcr.io/microrealestate/microrealestate/tenant-frontend:${MRE_VERSION:-latest}
    container_name: mre-tenant-frontend
    restart: unless-stopped
    environment:
      - BASE_PATH=/tenant
      - PORT=8190
      - DOCKER_GATEWAY_URL=http://gateway:8080
      - CORS_ENABLED=true
      - GATEWAY_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN:-localhost}:${APP_PORT:-80}
      - NODE_ENV=production
    expose:
      - '8190'
    networks:
      - net
    depends_on:
      - gateway
    labels:
      - "com.three-roots.description=MRE Tenant Frontend"
      - "com.three-roots.service=tenant-ui"

###############################################################################
# Volumes
###############################################################################
volumes:
  redis_data:
    name: three_roots_redis_data
  mongodb_data:
    name: three_roots_mongodb_data
  backup_data:
    name: three_roots_backup_data

###############################################################################
# Networks
###############################################################################
networks:
  net:
    name: three_roots_network
    driver: bridge
